"""empty message

Revision ID: 0a9c29eb200a
Revises: 59bc52f95358
Create Date: 2023-10-14 16:14:14.958064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9c29eb200a'
down_revision = '59bc52f95358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    with op.batch_alter_table('favcharacter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])

    with op.batch_alter_table('favplanets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])

    with op.batch_alter_table('favstarships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.Integer(), nullable=True))

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['model'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('passengers')
        batch_op.drop_column('length')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('surface_water')
        batch_op.drop_column('climate')
        batch_op.drop_column('orbital_period')

    with op.batch_alter_table('favstarships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user')

    with op.batch_alter_table('favplanets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user')

    with op.batch_alter_table('favcharacter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
