"""empty message

Revision ID: 59bc52f95358
Revises: 8ef4e4c54b83
Create Date: 2023-10-14 15:51:51.208428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bc52f95358'
down_revision = '8ef4e4c54b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favplanets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planets'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favcharacter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('starship_class', sa.String(length=100), nullable=True),
    sa.Column('pilots', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilots'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favstarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starships', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['starships'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favstarships')
    op.drop_table('starships')
    op.drop_table('favcharacter')
    op.drop_table('favplanets')
    op.drop_table('character')
    op.drop_table('planets')
    # ### end Alembic commands ###
